In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('Iris.csv')

In [3]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.shape

(150, 6)

In [6]:
X = df.iloc[:,:4].values
X

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  6. ,   5.4,   3.9,   1.7],
       [  7. ,   4.6,   3.4,   1.4],
       [  8. ,   5. ,   3.4,   1.5],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 13. ,   4.8,   3. ,   1.4],
       [ 14. ,   4.3,   3. ,   1.1],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   1.3],
       [ 18. ,   5.1,   3.5,   1.4],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 24. ,   5.1,   3.3,   1.7],
       [ 25. ,   4.8,   3.4,   1.9],
       [ 26. ,   5. ,   3. ,   1.6],
       [ 27. ,   5. ,   3.4,   1.6],
 

In [15]:
y = df['Species'].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 1.11213893,  1.06261558,  0.60360313,  1.09153375],
       [-0.69721014, -1.30105615, -0.1065182 , -1.34775345],
       [-0.07882502,  0.56500048, -1.29005375,  0.63771287],
       [ 1.20375154,  0.68940425, -0.57993242,  1.03480614],
       [-1.26978897, -0.5546335 ,  0.84031024, -1.17757062],
       [-1.01785428, -0.5546335 ,  0.84031024, -1.29102584],
       [ 0.97472001,  2.30665333, -1.05334664,  1.77226505],
       [ 0.31052858, -0.43022972, -1.29005375,  0.12716439],
       [-0.30785655,  0.19178915, -2.00017509,  0.12716439],
       [-0.74301645, -1.0522486 ,  1.07701735, -1.23429823],
       [ 0.8831074 , -0.0570184 , -0.57993242,  0.75116809],
       [ 0.35633489,  0.31619293, -0.1065182 ,  0.46753005],
       [-1.1094669 , -0.80344105,  1.07701735, -1.29102584],
       [ 0.79149479,  0.81380803,  0.36689602,  0.75116809],
       [ 1.34117046,  0.31619293, -1.05334664,  1.03480614],
       [ 0.99762317,  0.19178915, -2.00017509,  0.69444048],
       [-1.68204572, -1.

In [18]:
X_test

array([[-0.14753448, -0.30582595, -1.29005375,  0.07043678],
       [-0.19334078, -0.0570184 , -0.81663953,  0.183892  ],
       [ 0.53956011, -0.18142217, -0.57993242,  0.183892  ],
       [-1.08656374, -0.80344105,  0.84031024, -1.34775345],
       [-0.99495113, -0.80344105,  2.49726002, -1.29102584],
       [-0.92624167, -1.0522486 ,  0.36689602, -1.46120866],
       [ 1.59310514,  1.06261558, -0.1065182 ,  0.8078957 ],
       [ 1.13504208,  1.68463445,  0.36689602,  1.26171657],
       [-1.52172365, -1.17665237,  0.13018891, -1.29102584],
       [-0.67430699, -0.92784482,  1.78713869, -1.23429823],
       [-0.39946916,  0.9382118 , -0.34322531,  0.46753005],
       [ 0.28762543, -0.30582595, -0.1065182 ,  0.183892  ],
       [ 1.272461  ,  2.55546088,  1.78713869,  1.48862701],
       [-1.45301419, -1.30105615, -0.1065182 , -1.34775345],
       [ 0.60826957,  1.56023068, -0.1065182 ,  1.20498896],
       [ 1.24955785,  1.933442  , -0.57993242,  1.31844418],
       [-1.56752995, -1.

In [19]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [20]:
y_pred = classifier.predict(X_test)
y_pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica'],
      dtype='<U15')

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[10,  0,  0],
       [ 0, 12,  0],
       [ 0,  1,  7]])

In [22]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9666666666666667


In [23]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0   Iris-versicolor  Iris-versicolor
1   Iris-versicolor  Iris-versicolor
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4       Iris-setosa      Iris-setosa
5       Iris-setosa      Iris-setosa
6    Iris-virginica   Iris-virginica
7    Iris-virginica   Iris-virginica
8       Iris-setosa      Iris-setosa
9       Iris-setosa      Iris-setosa
10  Iris-versicolor  Iris-versicolor
11  Iris-versicolor  Iris-versicolor
12   Iris-virginica   Iris-virginica
13      Iris-setosa      Iris-setosa
14   Iris-virginica   Iris-virginica
15   Iris-virginica   Iris-virginica
16      Iris-setosa      Iris-setosa
17   Iris-virginica   Iris-virginica
18  Iris-versicolor  Iris-versicolor
19  Iris-versicolor  Iris-versicolor
20      Iris-setosa      Iris-setosa
21      Iris-setosa      Iris-setosa
22   Iris-virginica  Iris-versicolor
23  Iris-versicolor  Iris-versicolor
24  Iris-versicolor  Iris-versicolor
25  Iris-versicolor  Iris-versicolor
26      Iris-setosa      Iris-setosa
27  Iris-versicolor  Iris-versicolor
28  Iris-versicolor  Iris-versicolor
29   Iris-virginica   Iris-virginica